import json, sys

symbols = json.load(open(sys.argv[1]))

print('DEF(allproc, '+hex(symbols['allproc'])+')')
print('DEF(idt, '+hex(symbols['idt'])+')')
print('DEF(gdt_array, '+hex(symbols['gdt_array'])+')')
print('DEF(tss_array, '+hex(symbols['tss_array'])+')')
print('DEF(pcpu_array, '+hex(symbols['pcpu_array'])+')')
print('DEF(doreti_iret, '+hex(symbols['doreti_iret'])+')')
print('DEF(add_rsp_iret, doreti_iret - 7)')
print('DEF(swapgs_add_rsp_iret, doreti_iret - 10)')
print('DEF(rep_movsb_pop_rbp_ret, '+hex(symbols['rep_movsb_pop_rbp_ret'])+')')
print('DEF(rdmsr_start, '+hex(symbols['rdmsr_start'])+')')
print('DEF(wrmsr_ret, '+hex(symbols['wrmsr_ret'])+')')
print('DEF(dr2gpr_start, '+hex(symbols['dr2gpr_start'])+')')
print('DEF(gpr2dr_1_start, '+hex(symbols['gpr2dr_1_start'])+')')
print('DEF(gpr2dr_2_start, '+hex(symbols['gpr2dr_2_start'])+')')
print('DEF(mov_cr3_rax, '+hex(symbols['mov_cr3_rax'])+')')
print('DEF(mov_rdi_cr3, '+hex(symbols['mov_rdi_cr3'])+')')
print('DEF(nop_ret, wrmsr_ret + 2)')
print('DEF(cpu_switch, '+hex(symbols['cpu_switch'])+')')
print('DEF(mprotect_fix_start, '+hex(symbols['mprotect_fix_start'])+')')
print('DEF(mprotect_fix_end, mprotect_fix_start+6)')
print('DEF(mmap_self_fix_1_start, '+hex(symbols['mmap_self_fix_1_start'])+')')
print('DEF(mmap_self_fix_1_end, mmap_self_fix_1_start+2)')
print('DEF(mmap_self_fix_2_start, '+hex(symbols['mmap_self_fix_2_start'])+')')
print('DEF(mmap_self_fix_2_end, mmap_self_fix_2_start+2)')
print('DEF(sigaction_fix_start, '+hex(symbols['sigaction_fix_start'])+')')
print('DEF(sigaction_fix_end, '+hex(symbols['sigaction_fix_end'])+')')
print('DEF(sysents, '+hex(symbols['sysents'])+')')
print('DEF(sysents_ps4, '+hex(symbols['sysents_ps4'])+')')
print('DEF(sysentvec, '+hex(symbols['sysentvec'])+')')
print('DEF(sysentvec_ps4, '+hex(symbols['sysentvec_ps4'])+')')
print('DEF(sceSblServiceMailbox, '+hex(symbols['sceSblServiceMailbox'])+')')
print('DEF(sceSblAuthMgrSmIsLoadable2, '+hex(symbols['sceSblAuthMgrSmIsLoadable2'])+')')
print('DEF(mdbg_call_fix, '+hex(symbols['mdbg_call_fix'])+')')
print('DEF(syscall_before, '+hex(symbols['syscall_before'])+')')
print('DEF(syscall_after, '+hex(symbols['syscall_after'])+')')
print('DEF(malloc, '+hex(symbols['malloc'])+')')
print('DEF(M_something, '+hex(symbols['M_something'])+')')
print('DEF(loadSelfSegment_epilogue, '+hex(symbols['loadSelfSegment_epilogue'])+')')
print('DEF(loadSelfSegment_watchpoint, '+hex(symbols['loadSelfSegment_watchpoint'])+')')
print('DEF(loadSelfSegment_watchpoint_lr, '+hex(symbols['loadSelfSegment_watchpoint_lr'])+')')
print('DEF(decryptSelfBlock_watchpoint_lr, '+hex(symbols['decryptSelfBlock_watchpoint_lr'])+')')
print('DEF(decryptSelfBlock_epilogue, '+hex(symbols['decryptSelfBlock_epilogue'])+')')
print('DEF(decryptMultipleSelfBlocks_watchpoint_lr, '+hex(symbols['decryptMultipleSelfBlocks_watchpoint_lr'])+')')
print('DEF(decryptMultipleSelfBlocks_epilogue, '+hex(symbols['decryptMultipleSelfBlocks_epilogue'])+')')
print('DEF(sceSblServiceMailbox_lr_verifyHeader, '+hex(symbols['sceSblServiceMailbox_lr_verifyHeader'])+')')
print('DEF(sceSblServiceMailbox_lr_loadSelfSegment, '+hex(symbols['sceSblServiceMailbox_lr_loadSelfSegment'])+')')
print('DEF(sceSblServiceMailbox_lr_decryptSelfBlock, '+hex(symbols['sceSblServiceMailbox_lr_decryptSelfBlock'])+')')
print('DEF(sceSblServiceMailbox_lr_decryptMultipleSelfBlocks, '+hex(symbols['sceSblServiceMailbox_lr_decryptMultipleSelfBlocks'])+')')
print('DEF(sceSblServiceMailbox_lr_sceSblAuthMgrSmFinalize, '+hex(symbols['sceSblServiceMailbox_lr_sceSblAuthMgrSmFinalize'])+')')
print('DEF(sceSblServiceMailbox_lr_verifySuperBlock, '+hex(symbols['sceSblServiceMailbox_lr_verifySuperBlock'])+')')
print('DEF(sceSblServiceMailbox_lr_sceSblPfsClearKey_1, '+hex(symbols['sceSblServiceMailbox_lr_sceSblPfsClearKey_1'])+')')
print('DEF(sceSblServiceMailbox_lr_sceSblPfsClearKey_2, '+hex(symbols['sceSblServiceMailbox_lr_sceSblPfsClearKey_2'])+')')
print('DEF(sceSblPfsSetKeys, '+hex(symbols['sceSblPfsSetKeys'])+')')
print('DEF(sceSblServiceCryptAsync, '+hex(symbols['sceSblServiceCryptAsync'])+')')
print('DEF(sceSblServiceCryptAsync_deref_singleton, '+hex(symbols['sceSblServiceCryptAsync_deref_singleton'])+')')
print('DEF(copyin, '+hex(symbols['copyin'])+')')
print('DEF(copyout, '+hex(symbols['copyout'])+')')
print('DEF(crypt_message_resolve, '+hex(symbols['crypt_message_resolve'])+')')
print('DEF(justreturn, '+hex(symbols['justreturn'])+')')
print('DEF(justreturn_pop, justreturn+8)')
print('DEF(mini_syscore_header, '+hex(symbols['mini_syscore_header'])+')')
print('DEF(pop_all_iret, '+hex(symbols['pop_all_iret'])+')')
print('DEF(pop_all_except_rdi_iret, pop_all_iret+4)')
print('DEF(push_pop_all_iret, '+hex(symbols['push_pop_all_iret'])+')')
print('DEF(kernel_pmap_store, '+hex(symbols['kernel_pmap_store'])+')')
print('DEF(crypt_singleton_array, '+hex(symbols['crypt_singleton_array'])+')')
#print('DEF(security_flags, '+hex(symbols['security_flags'])+')')
#print('DEF(targetid, '+hex(symbols['targetid'])+')')
#print('DEF(qa_flags, '+hex(symbols['qa_flags'])+')')
#print('DEF(utoken, '+hex(symbols['utoken'])+')')

